export const MODAL_OPEN = "MODAL_OPEN";

export const LIBRARY_SELECTED = "LIBRARY_SELECTED";

export const LIBRARY_FETCH_REQUESTED = "LIBRARY_FETCH_REQUESTED";
export const LIBRARY_FETCH_SUCCEEDED = "LIBRARY_FETCH_SUCCEEDED";
export const LIBRARY_FETCH_FAILED = "LIBRARY_FETCH_FAILED";

export const LIBRARY_ADD_REQUESTED = "LIBRARY_ADD_REQUESTED";
export const LIBRARY_ADD_SUCCEEDED = "LIBRARY_ADD_SUCCEEDED";
export const LIBRARY_ADD_FAILED = "LIBRARY_ADD_FAILED";

export const LIBRARY_UPDATE_REQUESTED = "LIBRARY_UPDATE_REQUESTED";
export const LIBRARY_UPDATE_SUCCEEDED = "LIBRARY_UPDATE_SUCCEEDED";
export const LIBRARY_UPDATE_FAILED = "LIBRARY_UPDATE_FAILED";

export const LIBRARY_DELETE_REQUESTED = "LIBRARY_DELETE_REQUESTED";
export const LIBRARY_DELETE_SUCCEEDED = "LIBRARY_DELETE_SUCCEEDED";
export const LIBRARY_DELETE_FAILED = "LIBRARY_DELETE_FAILED";